# ---------------------------------------------------------------------------
# GUIDED RESEARCH
# ---------------------------------------------------------------------------

stages:
    - test

tests:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ./tester --gtest_filter=BTreeTest.*

linter:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ninja lint
    allow_failure: true