# ---------------------------------------------------------------------------
# GUIDED RESEARCH
# ---------------------------------------------------------------------------

stages:
    - test
    - bench

tests:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ./tester

linter:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
        - ninja lint
    allow_failure: true

benchmark:
    stage: bench
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
        - ninja
        - ./bench